import { safeNext } from "@/lib/auth/safe-next";
import { resolveCallbackResult } from "@/lib/auth/callback-handler";
import { NextResponse } from "next/server";

/**
 * `/auth/callback` — handles both the new token-hash flow and the legacy
 * PKCE code flow (backward compat during the email-template transition).
 *
 * ## Token formats
 *
 * **New (token-hash):**  `?token_hash=<hash>&type=email&next=/trips`
 *   Generated by the Supabase Dashboard "Magic Link" template when set to
 *   the token-hash variant. Self-contained — works cross-device/cross-browser.
 *   See #137.
 *
 * **Legacy (PKCE code):** `?code=<code>&next=/trips`
 *   The @supabase/ssr default. Requires the `code_verifier` cookie from
 *   the requesting browser. Breaks when the link is opened on a different
 *   device (AuthPKCECodeVerifierMissingError).
 *
 * token_hash takes precedence when both params are present (can happen
 * during the template-flip transition window).
 *
 * ## safeNext()
 * Collapses `null`, protocol-relative (`//evil.com/x`), off-origin
 * (`https://evil.com`), and scheme-prefixed (`javascript:alert(1)`)
 * inputs to the default `/trips` target. See `lib/auth/safe-next.ts`.
 */
export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);

  const params = {
    token_hash: searchParams.get("token_hash"),
    type: searchParams.get("type"),
    code: searchParams.get("code"),
    next: safeNext(searchParams.get("next")),
  };

  const result = await resolveCallbackResult(params);

  if (result.ok) {
    return NextResponse.redirect(`${origin}${result.next}`);
  }

  return NextResponse.redirect(`${origin}/login?error=auth`);
}
